name: d_bincode
description: >
  A performant bincode like serialization library for Dart. Manually writen, provides encoding for binary data structures, mirroring the bincode specification (Rust) minimalistically.
version: 3.0.0
license: 'MIT'

homepage: https://github.com/Binurie/d_bincode
repository: https://github.com/Binurie/d_bincode
issue_tracker: https://github.com/Binurie/d_bincode/issues
documentation: https://github.com/Binurie/d_bincode#readme
topics:
  - serialization
  - bincode
  - binary
  - dart

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:

dev_dependencies:
  lints: ^5.1.1
  intl: ^0.20.2
  benchmark: ^0.3.0
  test: ^1.25.15

